language: node_js
sudo: false
node_js:
- 8
# built by branches
branches:
  only:
  - master
  - develop
install:
- npm install
cache:
  bundler: true
  directories:
    - node_modules
script:
- npm run test
after_success:
- npm run build
